## Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6], [7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.91808792, 0.86494152, 0.73103227, 0.03570427, 0.54485828])

In [19]:
np.random.rand(5,5)

array([[0.48791338, 0.93167455, 0.0134018 , 0.04086348, 0.13709267],
       [0.12322657, 0.81677112, 0.72516433, 0.8747328 , 0.30658918],
       [0.59772849, 0.42330453, 0.9592572 , 0.47982998, 0.74922247],
       [0.40754563, 0.19645813, 0.64863377, 0.54656295, 0.60415274],
       [0.73279935, 0.66027431, 0.83013376, 0.63548023, 0.80577013]])

In [20]:
np.random.randn(2)

array([0.19285228, 1.54675612])

In [21]:
np.random.rand(4)

array([0.67267554, 0.51690874, 0.95881495, 0.00824325])

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0, 50, 10)

In [25]:
ranarr

array([22, 36,  4, 40, 19, 25, 31, 16, 29, 22])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr

array([22, 36,  4, 40, 19, 25, 31, 16, 29, 22])

In [30]:
ranarr.max()

40

In [31]:
ranarr.min()

4

In [32]:
ranarr.argmax()

3

In [33]:
ranarr.argmin()

2

In [34]:
arr.shape

(25,)

In [35]:
arr = arr.reshape(5,5)

In [36]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.shape

(5, 5)

In [38]:
arr.dtype

dtype('int64')

In [39]:
from numpy.random import randint

In [40]:
randint(2,10)

7