In [8]:
import numpy as np

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[9]

9

In [14]:
arr[1:5]

array([1, 2, 3, 4])

In [15]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [17]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [18]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [19]:
arr[0:5] = 100

In [20]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
arr = np.arange(0,11)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
slice_of_arr = arr[0:6]

In [24]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [25]:
slice_of_arr[:] = 99

In [26]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr_copy = arr.copy()

In [29]:
arr_copy[:] = 100

In [30]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [31]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [32]:
arr_2d = np.array([[5,10,15], [20,25, 30],[35,40,45]])

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d[1,2]

30

In [35]:
arr_2d[1][2]

30

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr = np.arange(1,11)

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
bool_arr = arr > 5

In [42]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [43]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [44]:
arr_2d = np.arange(50).reshape(5,10)

In [45]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [46]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [47]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])